### PR TITLE
Atlassian Datathon Webpage

### PR DESCRIPTION
**Pull request by MillenniumForce**
Let us know if there's anything we forgot to add or anything that's incorrect.

Also wasn't sure what the title of the Datathon was so I just went off of what Aileen told me

### CODE REVIEW

**Comment by William-Feng** [comment]
Thanks for working on it! I've added a popup so that people can easily notice this page.

Could you please also make the headings a little less obtrusive - the Prizes, Our Partners, Register Here, FAQs

**Comment by MillenniumForce** [comment]
@William-Feng what do you mean by less obtrusive exactly?

**Comment by William-Feng** [comment]
Right now the gradient background for the heading seems quite jarring from the rest of the text (and the fact that it spans all the way across the page). See if you guys can find a colour scheme/design that would make the headings stand out, but won't look completely random.

Appreciate it @amber-dang @MillenniumForce, and I think it's possible to include such a new design for our 'About' page later on too, so your efforts won't be limited to just this temporary page!

**Comment by MillenniumForce** [comment]
Oh gotcha yeah I agree I'll see what I can do

**Comment by MillenniumForce** [comment]
@William-Feng take a look now. I made the banners all a consistent colour which I thought looked better then the previous ones since it's now more consistent. Let me know what you think/any improvements.

**Comment by William-Feng** [comment]
Should be fine, we'll push to master after our meeting on Monday - thanks!

**Comment by piratre** [comment]
Looks good to me: thanks for all the work Julian!

If you have time, probably start thinking about how you can generalise the page into a template, because we probably don't want to redo the whole thing for Mirvac, but yes, we can push to master on Monday

**Comment by piratre** [comment]
For the questions "I've never done this before" and "Should I join even if I have limited knowledge", now the sentiment leans towards discouragement (i.e., we've overcorrected somewhat). We want it to be mostly neutral/professional. So make no promises (no 'YES!') but instead say something like "It will be a good experience for all participants regardless of skill level," or "Our workshops/mentoring sessions will be there to guide everyone throughout the week." Mainly the sentiment we want to convey is, please participate, but at the same time we want to avoid making promises about the datathon being definitely suitable for all skill levels, and yet also avoid mentions of who it would NOT be suitable for (basically, total, professional ambiguity).

Additionally, an FAQ on whether or not individuals are guaranteed a team would probably be good.

Thank you Julian!

**Comment by MillenniumForce** [comment]
@piratre take a look now should be fixed

**Comment by piratre** [comment]
Looks good to me!

**Comment by William-Feng** [comment]
One last thing we need to change the background.
Can you please use the cover photo from Facebook to see whether it works (removing the current logo and text)? If not, let us know if it would be better leaving what we've got but using a clean cover photo (without the info) as the background instead. Thanks again for your work!

**Comment by piratre** [comment]
We're requesting the textless CP background from marketing so probably wait on that

**Pull request merged**
