### PR TITLE
Newsletter subscription form

### PR DESCRIPTION
**Pull request by dqna64**
Updated newsletter subscription form in the Contacts page to include extra fields e.g. Degree, Year, Gender etc.

### CODE REVIEW

**Comment by piratre** [comment]
While a functional design that nicely integrates the mailchimp form, it leaves a bit too much whitespace on the contact page. Think about how you can move things around or add things to try and fill up this whitespace.

**Comment by dqna64** [comment]
Contacts page: I have reduced whitespace by making Mailchimp form more compact and rearranging some element on the page.

Outdated social media logos have been updated with latest brand assets.

I have also revised the contacts page text. Feel free to rephrase or reject edits or provide alternatively text, and I will update as required.

**Comment by William-Feng** [comment]
Great work Gordon, the design is much better now!

Could you please include replace the html for the subscription form currently located in _includes/subscription-form.html rather than directly adding it to contact.md?

Also please visit https://us19.admin.mailchimp.com/lists/integration/embeddedcode?id=117113 to get the refined HTML code for the form (I added a 'Required' condition for the fields since all this work would be useless if students didn't add their gender/degree details).

**Comment by dqna64** [comment]
> Also please visit https://us19.admin.mailchimp.com/lists/integration/embeddedcode?id=117113 to get the refined HTML code for the form (I added a 'Required' condition for the fields since all this work would be useless if students didn't add their gender/degree details).

Hey William, thanks for the directions. Is it okay if you show me exactly what changes were made to the MailChimp HTML code? Is it just added the 'Required' condition to all fields? I have made some substantial modifications to the MC HTML code so I need to add your changes manually.

**Comment by William-Feng** [comment]
Hey Gordon, yep all I did was add the 'Required' condition. I just manually added the span classes to the HTML code, which was a lot easier. All good now :)

**Pull request merged**
