### PR TITLE
Home page design

### PR DESCRIPTION
**Pull request by dqna64**
Re-structure and style home page. Add jobs board preview.

### CODE REVIEW

**Comment by William-Feng** [comment]
Great work @dqna64 !! I think the background colour styling looks nice for our website, so could you please incorporate that slightly darker hue for all the webpages (not just limited to the home page)? Thanks Gordon!

**Comment by dqna64** [comment]
Hey @William-Feng, I've added the background shade by declaring a new class name `background-shade` in bulma.css and adding the class name to all pages where the background shade is looks good ie. pages with content show on cards. Let me know what you think!

**Comment by William-Feng** [comment]
With the exception of maybe the sponsors page, I think you can use the background shade for all other pages (including Our  Team, Blog/Topics, Publications and Contact) - just so that there is a little more consistency with the background colour. Cheers Gordon!!

**Comment by William-Feng** [comment]
@dqna64 I've merged your changes into master but check out the website on mobile. The **home page photo** is repeating itself (check CSS) and the **sponsors** are not rendering properly (even if you hold your phone sideways) - consider using a flexbox.

Please fix these changes ASAP (**by tomorrow arvo**) as there are already people visiting our website due to the Datathon signups. Thank you

**Pull request merged**
